# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProtoTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProtoTest
  pod 'GTMSessionFetcher/Core', '~> 1.1'
  pod 'SwiftProtobuf', '~> 1.4'
end
